//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEdoc2017.Controllers.PHICService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PHICService.PHICServiceSoap")]
    public interface PHICServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPatientRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEdoc2017.Controllers.PHICService.PatientData GetPatientRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPatientRecords", ReplyAction="*")]
        System.Threading.Tasks.Task<WebEdoc2017.Controllers.PHICService.PatientData> GetPatientRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocumentCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEdoc2017.Controllers.PHICService.PatientData GetDocumentCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocumentCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<WebEdoc2017.Controllers.PHICService.PatientData> GetDocumentCategoryAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PatientData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataTable dtField;
        
        private bool isValidField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Data.DataTable dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
                this.RaisePropertyChanged("dt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool isValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("isValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PHICServiceSoapChannel : WebEdoc2017.Controllers.PHICService.PHICServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PHICServiceSoapClient : System.ServiceModel.ClientBase<WebEdoc2017.Controllers.PHICService.PHICServiceSoap>, WebEdoc2017.Controllers.PHICService.PHICServiceSoap {
        
        public PHICServiceSoapClient() {
        }
        
        public PHICServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PHICServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PHICServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PHICServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public WebEdoc2017.Controllers.PHICService.PatientData GetPatientRecords() {
            return base.Channel.GetPatientRecords();
        }
        
        public System.Threading.Tasks.Task<WebEdoc2017.Controllers.PHICService.PatientData> GetPatientRecordsAsync() {
            return base.Channel.GetPatientRecordsAsync();
        }
        
        public WebEdoc2017.Controllers.PHICService.PatientData GetDocumentCategory() {
            return base.Channel.GetDocumentCategory();
        }
        
        public System.Threading.Tasks.Task<WebEdoc2017.Controllers.PHICService.PatientData> GetDocumentCategoryAsync() {
            return base.Channel.GetDocumentCategoryAsync();
        }
    }
}
